# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-18 02:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createDate', models.DateField(auto_now_add=True)),
                ('modifyDate', models.DateField(auto_now=True)),
                ('projectName', models.CharField(max_length=128, verbose_name='Project name')),
                ('logo', models.ImageField(blank=True, upload_to=b'projects/logos', verbose_name='Project logo')),
                ('homepage', models.URLField(blank=True, verbose_name='Project homepage url')),
                ('descriptionDE', models.TextField(verbose_name='Description text of your project (German)')),
                ('descriptionEN', models.TextField(verbose_name='Description text of your project (English)')),
                ('boothPreferedLocation', models.PositiveIntegerField(choices=[(1, 'Main Floor'), (2, 'Stage'), (0, 'No preference')], default=0, verbose_name='Do you have a preferred location for your booth?')),
                ('boothNumTables', models.PositiveIntegerField(blank=True, null=True, verbose_name='How many tables do you need (roughly 1.20m x 0.80m)?')),
                ('boothNumChairs', models.PositiveIntegerField(blank=True, null=True, verbose_name='How many chairs do you need?')),
                ('boothPower', models.PositiveIntegerField(blank=True, null=True, verbose_name='Do you need power? (How many kwH)')),
                ('boothArea', multiselectfield.db.fields.MultiSelectField(choices=[(1, '3D Printing'), (2, 'Arduino'), (3, 'Art'), (4, 'Biohacking'), (5, 'Bionics'), (6, 'Crafts'), (7, 'Design'), (8, 'Digital Fabrication'), (9,
                ('boothComment', models.TextField(blank=True, verbose_name='Here you have the chance to leave us further comments regarding your booth:')),
                ('talkComment', models.TextField(blank=True, verbose_name='Here you have the chance to leave us further comments regarding your talk:')),
                ('workshopComment', models.TextField(blank=True, verbose_name='Here you have the chance to leave us further comments regarding your workshop:')),
                ('accepted', models.BooleanField(default=False, editable=False)),
                ('year', models.PositiveIntegerField(editable=False, verbose_name='Conference year this project belongs to')),
                ('owner', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, editable=False, related_name='projectparticipation', through='project.ProjectParticipants', to=settings.AUTH_USER_MODEL),
        ),
    ]

