# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import sabot.utils


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_auto_20160225_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template',
            field=models.FileField(upload_to=sabot.utils.upload_transform_func, verbose_name='Invoice template file (odt)'),
        ),
    ]
